import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '@components/Header'
import Body from '@components/Data/Body'
import { promises as fs } from 'fs'
import path from 'path'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'



export default function Home({res}) {


  

  return (
    <div>
      <Head>
        <title>Furlough By Constituency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/qoe0ctl.css"></link>
      </Head>

      <Header />

      <Container fluid>

        <Row className="justify-content-md-center">
          <Col lg="8">
          <Body body={res}></Body>
          </Col>
          </Row>

      </Container>


    </div>
  )
}

export async function getStaticProps(context) {
  
  const postsDirectory = path.join(process.cwd(), 'data')
  const filenames = await fs.readdir(postsDirectory)

  const posts = filenames.map(async (filename) => {
    const filePath = path.join(postsDirectory, filename)
    const fileContents = await fs.readFile(filePath, 'utf8')

    const data = JSON.parse(fileContents)
  
    return data
  })

  return {
    props: {
      res: await Promise.all(posts),
    },
  }
}

